ALIASING_DICT = {
        "flip_pot_upright_in_sink_distractors": "flip_pot_upright_which_is_in_sink",
        "put_eggplant_into_pan": "put_eggplant_in_pot_or_pan",
        "put_eggplant_into_pot_or_pan": "put_eggplant_in_pot_or_pan",
        "faucet_front_to_left": "turn_faucet_front_to_left",
        "put_cup_from_counter_or_drying_rack_into_sink": "put_cup_from_anywhere_into_sink",
        "put_green_squash_into_pot_or_pan": "put_green_squash_in_pot_or_pan",
        "turn_lever_vertical_to-front": "turn_lever_vertical_to_front",
        "turn_lever_vertical_to_front_distractors": "turn_lever_vertical_to_front",
        "put_pan_from_sink_into_drying_rack": "put_pot_or_pan_from_sink_into_drying_rack",
        "put_corn_in_pan_which_is_on_stove_distractors": "put_corn_into_pot_or_pan",
        "put_corn_in_pan_which-is_on_stove_distractors": "put_corn_into_pot_or_pan",
        "put_corn_in_pot_which_is_in_sink_distractors": "put_corn_into_pot_or_pan",
        "take_broccoli_out_of_pan": "take_broccoli_out_of_pot_or_pan",
        "put_pepper_in_pan": "put_pepper_in_pot_or_pan",
        "put_sweet_potato_in_pot_which_is_in_sink_distractors": "put_sweet_potato_in_pot",
        "put_sweet_potato_in_pan_which_is_on_stove_distractors": "put_sweet_potato_in_pan_which_is_on_stove",
        "put_pan_in_sink": "put_pot_or_pan_in_sink",
        "put_pot_in_sink": "put_pot_or_pan_in_sink",
        "put_pan_from_stove_to_sink": "put_pot_or_pan_in_sink",
        "put_pot_on_stove_which_is_near_stove_distractors": "put_pot_or_pan_on_stove",
        "put_pan_on_stove_from_sink": "put_pot_or_pan_on_stove",

        "put_broccoli_in_pot_cardboardfence": "put_broccoli_in_pot_or_pan",
        "put_carrot_on_plate_cardboardfence": "put_carrot_on_plate",
        "take_broccoli_out_of_pan_cardboardfence": "take_broccoli_out_of_pot_or_pan",
        "take_carrot_off_plate_cardboardfence": "take_carrot_off_plate",

        'open_cabinet': 'open_door',
        'open_oven': 'open_door',
        'open_low_fridge': 'open_door',
        'open_fridge': 'open_door',
        'open_microwave': 'open_door',
        'open_microwave_2': 'open_door',
        'open_microwave_2_few_demo': 'open_door',
        'open_microwave_3': 'open_door',
        'open_microwave_4': 'open_door',
        'open_microwave_6': 'open_door',
        'open_microwave_half': 'open_door',

        'close_oven': 'close_door',
        'close_fridge': 'close_door',
        'close_cabinet': 'close_door',
        'close_low_fridge': 'close_door',
        'close_microwave': 'close_door',
        'close_microwave_2': 'close_door',
        'close_microwave_3': 'close_door',
        'close_microwave_4': 'close_door',
        'close_microwave_6': 'close_door',

}

_ALIASING_DICT = {
        "flip_pot_upright_in_sink_distractors": "flip_pot_upright_which_is_in_sink",
        "put_eggplant_into_pan": "put_eggplant_in_pot_or_pan",
        "put_eggplant_into_pot_or_pan": "put_eggplant_in_pot_or_pan",
        "faucet_front_to_left": "turn_faucet_front_to_left",
        "put_cup_from_counter_or_drying_rack_into_sink": "put_cup_from_anywhere_into_sink",
        "put_green_squash_into_pot_or_pan": "put_green_squash_in_pot_or_pan",
        "turn_lever_vertical_to-front": "turn_lever_vertical_to_front",
        "turn_lever_vertical_to_front_distractors": "turn_lever_vertical_to_front",
        "put_pan_from_sink_into_drying_rack": "put_pot_or_pan_from_sink_into_drying_rack",
        "put_corn_in_pan_which_is_on_stove_distractors": "put_corn_into_pot_or_pan",
        "put_corn_in_pan_which-is_on_stove_distractors": "put_corn_into_pot_or_pan",
        "put_corn_in_pot_which_is_in_sink_distractors": "put_corn_into_pot_or_pan",
        "take_broccoli_out_of_pan": "take_broccoli_out_of_pot_or_pan",
        "put_pepper_in_pan": "put_pepper_in_pot_or_pan",
        "put_sweet_potato_in_pot_which_is_in_sink_distractors": "put_sweet_potato_in_pot",
        "put_sweet_potato_in_pan_which_is_on_stove_distractors": "put_sweet_potato_in_pan_which_is_on_stove",
        "put_pan_in_sink": "put_pot_or_pan_in_sink",
        "put_pot_in_sink": "put_pot_or_pan_in_sink",
        "put_pan_from_stove_to_sink": "put_pot_or_pan_in_sink",
        "put_pot_on_stove_which_is_near_stove_distractors": "put_pot_or_pan_on_stove",
        "put_pan_on_stove_from_sink": "put_pot_or_pan_on_stove",

        "put_broccoli_in_pot_cardboardfence": "put_broccoli_in_pot_or_pan",
        "put_carrot_on_plate_cardboardfence": "put_carrot_on_plate",
        "take_broccoli_out_of_pan_cardboardfence": "take_broccoli_out_of_pot_or_pan",
        "take_carrot_off_plate_cardboardfence": "take_carrot_off_plate",

        'open_cabinet': 'open_door',
        'open_oven': 'open_door',
        'open_low_fridge': 'open_door',
        'open_fridge': 'open_door',
        'open_microwave': 'open_door',
        'open_microwave_2': 'open_door',
        'open_microwave_2_5pos_20neg': 'open_door',
        'open_microwave_2_1pos_20neg': 'open_door',
        'open_microwave_2_few_demo': 'open_door',
        'open_microwave_2_few_demo_with_neg': 'open_door',
        'open_microwave_3': 'open_door',
        'open_microwave_3_with_neg': 'open_door',
        '1014_all': 'open_door',
        'open_microwave_4': 'open_door',
        'open_microwave_6': 'open_door',

        'close_oven': 'close_door',
        'close_fridge': 'close_door',
        'close_cabinet': 'close_door',
        'close_low_fridge': 'close_door',
        'close_microwave': 'close_door',
        'close_microwave_2': 'close_door',
        'close_microwave_3': 'close_door',
        'close_microwave_4': 'close_door',
}

ALIASING_DICT.update(_ALIASING_DICT)

def get_aliased_name(name):
    if name in ALIASING_DICT:
        return ALIASING_DICT[name]
    return name